global:

  scrape_interval: 15s 

scrape_configs:
  # prometheus monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # python exporter monitoring
  - job_name: 'db_metrics_exporter'
    static_configs:
      - targets: ['data_generator:8000']